CREATE TABLE `user_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`onboardingStep` int NOT NULL DEFAULT 0,
	`onboardingCompleted` int NOT NULL DEFAULT 0,
	`age` int,
	`gender` varchar(32),
	`heightCm` int,
	`weightKg` int,
	`fitnessLevel` varchar(32),
	`primaryGoal` varchar(64),
	`secondaryGoal` varchar(64),
	`workoutDaysPerWeek` int,
	`workoutDurationMinutes` int,
	`preferredWorkoutTime` varchar(16),
	`environment` varchar(32),
	`equipment` text,
	`exerciseExclusions` text,
	`sleepQuality` int,
	`fatigueLevel` int,
	`recoveryFeeling` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_profiles_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_profiles_userId_unique` UNIQUE(`userId`)
);
