export const ENV = {
  appId: process.env.VITE_APP_ID || "adaptive-fitness",
  cookieSecret: process.env.JWT_SECRET || "adaptive_fitness_default_secret_key_2026_change_in_prod",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  authMode: process.env.AUTH_MODE ?? "mock",
  authOtpMode: process.env.AUTH_OTP_MODE ?? "mock",
  authEmailMode: process.env.AUTH_EMAIL_MODE ?? "mock",
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID ?? "",
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN ?? "",
  twilioPhoneNumber: process.env.TWILIO_PHONE_NUMBER ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendFromEmail: process.env.RESEND_FROM_EMAIL ?? "",
};
